{
    'name': 'Contratos Recurrentes a Medida (Cositt)',
    'version': '19.0.2.0.30',
    'category': 'Sales',
    'summary': 'Gestor de Contratos Recurrentes',
    'author': 'Cositt / Gerard Perat',
    'depends': [
        'website',
        'sale',
        'sale_management',
        'account',
        'mail',
        'sales_team',
        'project',
        'hr_timesheet',
        'sale_project',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/res_company_views.xml',
        'data/cron.xml',
        'data/mail_templates.xml',
        'data/mail_template_signature.xml',
        'data/mail_template_signed_copy.xml',
        'report/signature_evidence_templates.xml',
        'report/signature_evidence_report.xml',
        'views/product_template_views.xml',
        'views/subscription_contract_views.xml',
        'views/sale_order_views.xml',
        'views/website_templates.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'AGPL-3',
}
